[tool.poetry]
name = "dtm"
version = "0.2.1"
description = ""
authors = ["tovop <pev@sevassp.com>",
           "EBGlom <ebg@sevassp.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
nox = "^2022.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
