name: Build and test package

on: [push]

jobs:
  build:

    name: Test with ${{matrix.python}} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry


      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Run tests with Nox
        run: poetry run nox -s lint tests
