name: Publish Python package to Packagr

on:
  release:
    types: [created, edited]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Install poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install --with dev

    - name: Run tests
      run: poetry run nox -s tests
    - name: Publish package
      run: |
        poetry config repositories.packagr ${{ secrets.PACKAGR_REPOSITORY_URL }}
        poetry config http-basic.packagr ${{ secrets.PACKAGR_USERNAME }} ${{ secrets.PACKAGR_PASSWORD }}
        poetry publish --build --repository packagr
